[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet] # use for deployment
counter = "AzaKBxWEjJoiN4gU9hoierG8JqfqQdsGoQvVVhnii8Kt" # use for deployment

[programs.localnet]
counter = "AzaKBxWEjJoiN4gU9hoierG8JqfqQdsGoQvVVhnii8Kt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet" # use for deployment
# cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


